server:
  port: 7000

spring:
  application:
    name: order-service

# ============================================
# 🛡️ RESILIENCE4J CIRCUIT BREAKER CONFIG
# ============================================
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:                          # ← Product Service CB
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10



  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 3
        waitDuration: 1s

  timelimiter:
    instances:
      orderServiceCB:
        timeoutDuration: 5s


